apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: http-echo
spec:
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: echo
      image: inanimate/echo-server
      ports:
        - name: http
          port: 8080
      publicPort: http
      ingressConfiguration:
        - stickysessions
      environmentConfig:
        - environment: prod
          replicas: 10
  dnsAppAlias:
    environment: prod
    component: echo
